@ranker_HostAddress = http://localhost:5196

GET {{ranker_HostAddress}}/api/health
Accept: application/json

###

GET {{ranker_HostAddress}}/health
Accept: application/json

###

GET {{ranker_HostAddress}}/api/categories
Accept: application/json

###
